### ISSUE TITLE
NameError: name 'convert_model' is not defined

### ISSUE THREAD

**Issue by jaymefosa** [RohanChacko/PeeledHuman#3]
```
Traceback (most recent call last):
  File "test.py", line 119, in <module>
    model = create_model(opt)   # create a model given opt.model and other options
  File "/media/fsa/DATA/Work/GIST/PeeledHuman/models/__init__.py", line 68, in create_model
    instance = model(opt)
  File "/media/fsa/DATA/Work/GIST/PeeledHuman/models/pix2pix_model.py", line 50, in __init__
    not opt.no_dropout, opt.init_type, opt.init_gain, self.gpu_ids)
  File "/media/fsa/DATA/Work/GIST/PeeledHuman/models/networks.py", line 149, in define_G
    return init_net(net, init_type, init_gain, gpu_ids)
  File "/media/fsa/DATA/Work/GIST/PeeledHuman/models/networks.py", line 115, in init_net
    net = convert_model(net)
NameError: name 'convert_model' is not defined

```

**Comment by RohanChacko** [comment]
Hi,
I've updated the codebase. Please use the latest version. `convert_model` was part of the [synchronized batchnorm](https://github.com/vacancy/Synchronized-BatchNorm-PyTorch) implementation. You are free to not use it during inference.
